### ISSUE TITLE
requests.exceptions.HTTPError on running example code

### ISSUE THREAD

**Issue by leowhitehead** [vCra/judge0api#1]
When I run the usage example from the README, I get the following response.

```
Traceback (most recent call last):
  File "main.py", line 9, in <module>
    expected_output=b"Hello Judge0"
  File "/home/user/.local/lib/python3.6/site-packages/judge0api/submission.py", line 217, in submit
    submission.submit(client)
  File "/home/user/.local/lib/python3.6/site-packages/judge0api/submission.py", line 169, in submit
    r.raise_for_status()
  File "/home/user/.local/lib/python3.6/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.judge0.com/submissions/?base64_encoded=true&wait=true
```

**Comment by ia03** [comment]
This is probably because `wait=true` is not supported by the public Judge0 API. I got this error and fixed it by self-hosting the API.

**Comment by vCra** [comment]
Hey - sorry I've just seen this - I'll have a look at this tomorrow

**Comment by vCra** [comment]
Hi @lduck11007. I've updated the docs. Let me know if you still have any issues.
